<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">

		<label class="group-name" for="bt_height"><?php echo _t('ext.bt_videos.height'); ?></label>
		<div class="group-controls">
			<input type="number" id="bt_height" name="bt_height" value="<?php echo $this->getHeight(); ?>" min="50" data-leave-validation="1">
		</div>

		<label class="group-name" for="bt_width"><?php echo _t('ext.bt_videos.width'); ?></label>
		<div class="group-controls">
			<input type="number" id="bt_width" name="bt_width" value="<?php echo $this->getWidth(); ?>" min="100" data-leave-validation="1">
		</div>
		
		
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>

<p>
	<?php echo _t('ext.bt_videos.updates'); ?>
	<a href="https://github.com/kevinpapst/freshrss-youtube" target="_blank">GitHub</a>.
</p>
